# Generated by Django 4.0.1 on 2022-06-24 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_rename_comment_commentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='liked',
        ),
    ]
