# Generated by Django 4.0.1 on 2022-06-24 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0006_remove_postmodel_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='unlike',
            field=models.ManyToManyField(blank=True, default=None, related_name='unliked', to=settings.AUTH_USER_MODEL),
        ),
    ]
